### ISSUE TITLE
no extractable files found: docker using Unraid OS

### ISSUE THREAD

**Issue by kindiboy** [davidnewhall/unpackerr#156]
Hello, 

Setup:
All shares are there to store files
Unassigned Drive for downloads.

Log:
2021/10/05 16:24:14 [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/10/05 16:26:14 [Radarr] Updated (http://192.168.100.8:7878/radarr): 0 Items Queued
2021/10/05 16:26:14 [Sonarr] Updated (http://192.168.100.8:8989/sonarr): 3 Items Queued
2021/10/05 16:26:14 [Sonarr] Completed item still waiting: ****************************, no extractable files found at:
/data/**************************** (stat err: stat /data/****************************: no such file or directory)

I'm pretty green to this so any help would be greatly appreciated. Thank you

**Comment by davidnewhall** [comment]
Probably easier to help with initial setup in Discord. You have your `/data` mount setup wrong from the looks of it. The default is `/downloads` but if you're using `/data` you need to correct that in the container configuration.

**Comment by lawrence1986101** [comment]
im having the same issues it sees Sonarr it sees what I downloaded but after 1 min of waiting it just starts to err out maybe its just me or im not placing something in the right sport

**Comment by davidnewhall** [comment]
If it's the same issue then maybe it's the same fix. Can help more of you share your configurations.

**Comment by lawrence1986101** [comment]
I think I can get the logs. and mounts um, my unraid set up is simple Downloads goes to downloads son, rad,lid, and in downloads, there are 2 miles completed and incomplete Downloads Location: 
would be /mnt/user/Downloads/Download Path Downloadsi have the API and URL all Taken care of cant really mess that up im going to Guess i have something pointed the wrong way here 
    On Saturday, October 9, 2021, 11:21:06 PM EDT, nitsua ***@***.***> wrote:  
 
 


Can you provide the logs? The mounts?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lawrence1986101** [comment]
2 mile is 2 files BTW it was a spelling error

**Comment by lawrence1986101** [comment]
also Lidar don't have a download path at all in docker so if someone downloads come zipped music files that won't ever work

**Comment by lawrence1986101** [comment]
Fixed it was a pointing path.... inside unpacked were it says "Path to find Sonarr downloads. Must be within /downloads location" the Issue with that it was clear on what it was saying but it wasn't. My downloads are Downloads, not downloads un-capped
