### ISSUE TITLE
folders: sub folder items extract into tracked item folder.

### ISSUE THREAD

**Issue by ZeroPoke** [davidnewhall/unpackerr#194]
https://pastebin.com/raw/7W4ALmKy

**Comment by Njinx** [comment]
Can you be more specific with your issue? A vague title and Pastebin link isn't that helpful. Looking at the Pastebin I'm guessing this is a feature request, correct?

**Comment by davidnewhall** [comment]
@Njinx - This users is watching a folder named `TV`. A folder named `STP` is copied into `TV` that contains sub folders with rar files. The things being extracted from those rar files ends up in the `STP` folder and not the sub folder where the rar files are at.

The request is for the extracted items to go back into the sub folder, not the tracked item folder (`STP` in this case). The conversation leading to this issue is in my Discord.

**Comment by Njinx** [comment]
@davidnewhall I see. While whether you want to implement this is obviously up to you, it looks like this feature is probably out of the scope of this project and @ZeroPoke might want to look into Sonarr or another media management program.

**Comment by davidnewhall** [comment]
It's not out of scope. It's a bug.
