### ISSUE TITLE
 process caused "exec: \"sh\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by Little709** [davidnewhall/unpackerr#29]
So I posted a few days ago. 

I seem to have found the issue, no idea how to solve it though:

If i open the console i get 

OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown

I'm running this on unraid. 

Appreciate the help!

**Comment by davidnewhall** [comment]
What you described is normal. There is no shell into the container and no way to open a console into it.

I'll have more for you soon.

**Comment by Little709** [comment]
So what you're saying is that it will not work for now?

**Comment by davidnewhall** [comment]
It will work. There's something wrong with the download location in your environment. I do not know. I recently made a lot of changes to this app, and renamed it. One of the changes is the ability to manually configure the download path. The new app is not in unraid yet, so I idon't have an easy way to direct you to using it. It does work though, and if you're technical enough you can figure it out. Otherwise, I hope too have this new app in unraid very soon.

**Comment by hotio** [comment]
@Little709 In the following hour Unpackerr should become available as `hotio/unpackerr`.

**Comment by davidnewhall** [comment]
It's currently available at `golift/unpackerr:master`. ;)

**Comment by hotio** [comment]
I meant to say, on Unraid CA, modified my comment.... :-)

**Comment by Little709** [comment]
Thanks guys. after some trial and horror. it works! awesome

**Comment by BoKKeR** [comment]
Could it be added? it would help others with debugging

**Comment by davidnewhall** [comment]
Not really anything in the container to debug. Adding more to the container adds things to debug though. I've been building from scratch a long time and much prefer it. @mrhotio makes a container with a shell, based on alpine I believe. Pretty much a drop-in replacement if you prefer that.
