### ISSUE TITLE
Readarr support 

### ISSUE THREAD

**Issue by binarygeek119** [davidnewhall/unpackerr#43]
Readarr is a new ebook fork of sonarr

**Comment by davidnewhall** [comment]
I'm probably going to need some help here. I installed and configured Readarr, added a few books, but nothing shows up. I probably don't have any good sources for that content, and thus I'm having a hard time getting _anything_ into the queue. I need to see some of the API responses from Readarr while there is something queued. Preferably something that's finished  downloading and needs to be extracted.

If you have some things in queue, please run this command (_adapt to your environment_).
```
curl -i 127.0.0.1:8787/api/v1/queue?apikey=your_api_key
```

If you can attach that to a [gist](https://gist.github.com), that'd be very helpful, otherwise you an find me on Discord: `TwitchCaptain#2728` - send me a PM. Thank you!

**Comment by davidnewhall** [comment]
Never mind. I got what I needed.

**Comment by davidnewhall** [comment]
Readarr support has been added. Works for me, although Readarr doesn't automatically import extracted items. I imagine in time they'll fix that. 

Try the `master` docker tag if you're using Docker. The variables are in the repo [README](https://github.com/davidnewhall/unpackerr/blob/master/README.md#docker-env-variables). I'll cut a new release soon.
