### ISSUE TITLE
Typo in provided unpackerr.conf

### ISSUE THREAD

**Issue by pkreuzt** [davidnewhall/unpackerr#65]
Example configs provided on deb packages (and probably others) have a line for "protocols" which reads:

   protocols = "torrents"

On https://github.com/davidnewhall/unpackerr/issues/60 you stated it should be "torrent". Could you modify next packages to spell it correctly?

On a sidenote, I'd recommend to add a Umask line on unpackerr.service or at least explain that possibility on documentation. Many people has a setup with different users for each *arr app and share a common group with their torrent client. The UMask parameter is a must with those setups.

Thanks

**Comment by davidnewhall** [comment]
> Could you modify next packages to spell it correctly?

It was already fixed here https://github.com/davidnewhall/unpackerr/pull/56 and will be correct in the next release.

> add a Umask line on unpackerr.service

I can add that. I generally just recommend folks fix/change the `user` (and/or add `group`) to the unit file. They could add `umask` too/instead. The next release allows [setting file and dir modes](https://github.com/davidnewhall/unpackerr/issues/54) within unpackerr, but umask may still be a necessary tunable to make things perfect.

**Comment by davidnewhall** [comment]
A new beta release has been created. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta1

It has the fix for the config file and adds user/group/umask to the linux packages (#66). To allow the Sonarr user to write to the files unpackerr creates, add it to the unpackerr group, ie. `usermod -G unpackerr sonarr`.

I have not tested any of the new linux package pieces, but plan to. I really appreciate any feedback you can provide!

**Comment by davidnewhall** [comment]
A working beta version is available now that should resolve this issue. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`

The previous beta mentioned was deleted because it was broken.
